name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ksh
      run: sudo apt-get install ksh

    - name: test
      run: ./tools/test

